### ISSUE TITLE
support for linux

### ISSUE THREAD

**Issue by moc67331** [Zuntan03/EasyNovelAssistant#1]
面白いツールをありがとうございます
これをlinuxに対応させる予定はあるでしょうか？

手元で試したところ、少しソースを修正し各スクリプトを用意したら動作しました。
https://github.com/moc67331/EasyNovelAssistant
ただし、確認環境は今の所arch linuxのみです

**Comment by moc67331** [comment]
マージありがとうございます！

度々すみません。Installスクリプトの記載に一部誤りがありました。
こちらのマージもお願いすることは可能でしょうか？
https://github.com/moc67331/EasyNovelAssistant/commit/71ff2d21676c774415fa2b6ea6ddc55905ef9154

またRun-EasyNovelAssistant.shも加えて頂けると嬉しいです。
（Run-EasyNovelAssistant.batのLinux版）
https://github.com/moc67331/EasyNovelAssistant/blob/main/Run-EasyNovelAssistant.sh

**Comment by Zuntan03** [comment]
修正と指摘、ありがとうございます。
対応しました。

**Comment by moc67331** [comment]
お手数おかけしました。ありがとうございます！
